# Generated by Django 3.2.5 on 2021-07-18 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Homeworld', models.CharField(max_length=100)),
                ('Films', models.CharField(max_length=500)),
                ('Species', models.CharField(max_length=500)),
                ('Vehicles', models.CharField(max_length=500)),
                ('Starships', models.CharField(max_length=500)),
                ('URL', models.CharField(max_length=500)),
            ],
        ),
    ]
