# Generated by Django 3.2.5 on 2021-07-18 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210718_0858'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='people',
            name='Name',
        ),
        migrations.AddField(
            model_name='people',
            name='birth_year',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='people',
            name='created',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='people',
            name='edited',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='people',
            name='eye_color',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='people',
            name='films',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='people',
            name='gender',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='people',
            name='hair_color',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='people',
            name='height',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='people',
            name='homeworld',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='people',
            name='mass',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='people',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='people',
            name='skin_color',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='people',
            name='species',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='people',
            name='starships',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='people',
            name='url',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='people',
            name='vehicles',
            field=models.CharField(default='', max_length=500),
        ),
    ]
